name: fennec
description:  Fennec is a multi-threaded, robust Dart Server-Side Framework.
version: 2.1.1
homepage: https://github.com/Fennec-Framework/fennec
issue_tracker: https://github.com/Fennec-Framework/fennec/issues

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  mime: ^1.0.2
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
